version: "3"
services:
  backend:
    build: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/tem"
      PORT: "3000"
    ports:
      - 3000:3000
  frontend:
    build: frontend
    environment:
      REACT_APP_API_URL: "http://localhost:3000"
      PORT: "8080"
      LOAD_SEED_DATA: false
    ports:
      - 8080:8080
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
